### PR TITLE
feat: added m4b getChapters api in getMediaInformation

### PR DESCRIPTION
**Pull request by Suman085**

### CODE REVIEW

**Comment by tanersener** [comment]
Could you provide a file to test this PR?

**Comment by Suman085** [comment]
@tanersener  I've added the code in the example project itself. But I am unable to find a smaller m4b file URL that we can use to test.

**Comment by tanersener** [comment]
Nevermind, I guess I can find a file. 

As far as I understand, chapters won't be available in the response of `_flutterFFprobe.getMediaInformation`, right? 
You need to use `_flutterFFprobe.executeWithArguments()` and append `-show_chapters` in your command to get them in the MediaInformation class.

**Comment by Suman085** [comment]
> Nevermind, I guess I can find a file.
> 
> As far as I understand, chapters won't be available in the response of `_flutterFFprobe.getMediaInformation`, right? You need to use `_flutterFFprobe.executeWithArguments()` and append `-show_chapters` in your command to get them in the MediaInformation class.

Yup, Correct. That's what I've added in this PR. But I needed to call the _flutterFFprobe.executeWithArguements(["-show_chapters]). Didnt get the reason behind it.

**Comment by tanersener** [comment]
`_flutterFFprobe.getMediaInformation()` implementation calls the parent project's `getMediaInformation()` method [here](https://github.com/tanersener/flutter-ffmpeg/blob/v0.4.2/android/src/main/java/com/arthenica/flutter/ffmpeg/FlutterFFmpegGetMediaInformationAsyncTask.java#L51) using the `path` passed.

And the command to get `MediaInformation` is hidden [there](https://github.com/tanersener/mobile-ffmpeg/blob/v4.4/android/app/src/main/java/com/arthenica/mobileffmpeg/FFprobe.java#L86) in `mobile-ffmpeg`. That's why it doesn't work. That command doesn't include `-show_chapters`.

**Comment by tanersener** [comment]
Well, changing the command will be difficult in this project. So, I suggest making these changes in the new plugin that will replace `flutter_ffmpeg`. Because `flutter_ffmpeg` will be retired in a few days time.

The new plugin is called `ffmpeg-kit`. See the [README](https://github.com/tanersener/ffmpeg-kit/tree/main/flutter/flutter).

**Comment by Suman085** [comment]
Sorry, got a bit busy. Made some time to create the PR on that repo but cannot find the example project to test.

**Comment by tanersener** [comment]
It's fine. I added the test app repository path in the new PR. You can test the changes there.

**Pull request closed without merging**
