### PR TITLE
Issue #283

### PR DESCRIPTION
**Pull request by AbhishekDoshi26**
Issue #283 solved with proguard file. Hence, I have added the instruction and the complete file in README.MD of the package so further users don't create any issue and can use the file directly.

### CODE REVIEW

**Comment by tanersener** [comment]
`proguard` solution is a workaround. Why are we promoting a workaround while we have a fix, something that we spent time on?

**Comment by AbhishekDoshi26** [comment]
@tanersener is the solution implemented? Because I myself got the issue today. It was just until the issue is not fixed, we can have proguard.

**Comment by tanersener** [comment]
The fix for `java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in` is given in the `Tips`. It was first reported in #237.

`If flutter_ffmpeg release builds on Android fail with the following exception, make sure that mavenCentral() is defined as a repository in your build.gradle and it is listed before jcenter().`

**Comment by AbhishekDoshi26** [comment]
@tanersener I tried the above solution and it works. Thanks.

**Comment by tanersener** [comment]
Which solution do you mean? We know both of them works. But we want people to use the fix, not the workaround. That's why I'm not convinced that we need to merge this PR.

**Pull request closed without merging**
