### PR TITLE
default packages changed to https/https-gpl

### PR DESCRIPTION
**Pull request by openponce**
default packages changed to https/https-gpl

### CODE REVIEW

**Comment by tanersener** [comment]
@openponce Could you please explain why we need this?

**Comment by diogoponce** [comment]
> @openponce Could you please explain why we need this?

Hello Taner Sener! How are you?
I needed to change this default as it is required for the plugin that developed OpenCamera (https://github.com/openponce/opencamera).
  The https-gpl configuration includes lib264 which I use to compress video and perform other operations. It would be very useful to have by default.
Would you like to avoid creating a project based on yours, could you make this small change? Thank you friend.

**Comment by diogoponce** [comment]
If you can release this update I am grateful, I am unable to publish my plugin on https://pub.dev as I am using as it depended on a github address.

**Comment by tanersener** [comment]
Hello @openponce I'm fine thanks.

`https` package is licensed under the `LGPL` and `https-gpl` is licensed under the `GPL`. It's not a good idea to change the default license to `GPL`.

Additionally, I have to remind that all users do not require `x264`. So I don't think that updating the default package is the right approach to solve your issue.

Why don't you use flutter_ffmpeg's `https-gpl` package in your case?

**Comment by diogoponce** [comment]
> Olá @openponce , estou bem, obrigado.
> 
> `https`O pacote é licenciado sob o `LGPL`e `https-gpl`é licenciado sob o `GPL`. Não é uma boa ideia alterar a licença padrão para `GPL`.
> 
> Além disso, devo lembrar que todos os usuários não precisam `x264`. Portanto, não acho que atualizar o pacote padrão seja a abordagem correta para resolver seu problema.
> 
> Por que você não usa o `https-gpl`pacote flutter_ffmpeg no seu caso?

Hello Taner Sener, thanks for the reply.
The problem I face is forcing the user to apply extra settings to use basic functions such as resizing or compressing videos.
The plugin I developed solves a recurring problem for flutter developers.
Could you take a look at my plugin?
Feel free to submit your pull request or submit your opinion.

**open camera plugin:** https://github.com/openponce/opencamera

Kind regards.

**Comment by diogoponce** [comment]
Note that it is very simple to use the plugin, just add the permissions and you're done! No extra setup!
If you can help me use your plugin without adding extra settings I would be very grateful.
If you want to become a contributor let me know that I add you.
Kind regards.

**Comment by tanersener** [comment]
> The problem I face is forcing the user to apply extra settings to use basic functions such as resizing or compressing videos.

Can you please explain the problem here? There are lots of users who are using non-default `flutter_ffmpeg` packages and none of the suggested to change the default package before.

**Comment by tanersener** [comment]
@diogoponce do you have any comments about my last question?

**Pull request closed without merging**
